version: "2"

services:
  pi-ase:
    image: pricecs/ase:${PI_VERSION}
    env_file:
      - ./env_vars
    shm_size: 1g
    ports:
      - 8010:8010
    networks:
      - pingnet

  pi-aad:
    image: pricecs/aad_amt:${PI_VERSION}
    command: wait-for pingaccess:9000 -t 300 -- entrypoint.sh
    env_file:
      - ./env_vars
    networks:
      - pingnet

  pingaccess:
    image: pingidentity/pingaccess:5.3.0-edge
    env_file:
      - ~/.pingidentity/devops
      - ./env_vars
    environment: 
      - SERVER_PROFILE_URL=https://github.com/cprice-ping/Profile-API-Security.git
      - SERVER_PROFILE_PATH=pingaccess
      - VERBOSE=false
      - PA_LOG_LEVEL=INFO
    ports:
      - 443:443
      - 9000:9000
    networks:
      - pingnet-dmz
      - pingnet

networks:
    pingnet:
    pingnet-dmz:
